### ISSUE TITLE
License

### ISSUE THREAD

**Issue by igeligel** [3YOURMIND/difffify#2]
Let us choose a license for this project. I would recommend:

- MIT
- Apache 2.0

Please tell me if you have other opinions (i think those licenses are the most open ones)

**Comment by krysopath** [comment]
MIT is fine with me.

**Comment by jamesoshea** [comment]
Also fine with me. Will add now.

**Comment by jamesoshea** [comment]
Also fine with me.


---

Sent from my Windows Phone.


On Jun 30, 2018 17:14, krysopath <notifications@github.com> wrote:

MIT is fine with me.
